# -*- coding: utf-8 -*-
"""Projeto 1 Questao 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14LzVZUWXnYHHxLTJu_JfI1XwU957FXSh
"""

import random as random
from random import seed
from random import randint
from random import SystemRandom
import numpy as np
import matplotlib.pyplot as plt

#Probabilidade de 25% == 1/4
#Probabilidade de 33.3333% == 1/3
#Probabilidade de 50% == 1/2

# Criação da função Pulos que recebe o parametro casa, que é a casa em que o inseto começa 
def Pulos(casa):
  #Armadilha ainda desativada 
  armadilha=False
  #Contagem de saltos, armadilhas e visitas a casa 5
  Pulo=0
  TrapA=0
  TrapB=0
  Visita5=0
  #Ciclo que acompanha o inseto até ser pego pela armadilha
  while(armadilha==False):
    if casa==1:
      armadilha=True
      #Modificação para contagem de capturas pela armadilha A
      TrapA+=1
    elif casa==2:  
      #Dado pela matriz de transição a probabilidade nas casas 2,4,6,8 tem probabilidade de 1/3 para as casa adjacentes
      casa= random.SystemRandom().choice([1,3,5])
      Pulo+=1
    elif casa==3:
      #Dado pela matriz de transição a probabilidade nas casas 3,7 tem probabilidade de 1/2 para as casa adjacentes
      casa= random.SystemRandom().choice([2,6])
      Pulo+=1
    elif casa==4:
      #Dado pela matriz de transição a probabilidade nas casas 2,4,6,8 tem probabilidade de 1/3 para as casa adjacentes
      casa= random.SystemRandom().choice([1,5,7])
      Pulo+=1
    elif casa==5:
      #Dado pela matriz de transição a probabilidade na casa 5 tem probabilidade de 1/4 para as casa adjacentes
      casa=random.SystemRandom().choice([2,4,6,8])
      Pulo+=1
      Visita5+=1
    elif casa==6:
      #Dado pela matriz de transição a probabilidade nas casas 2,4,6,8 tem probabilidade de 1/3 para as casa adjacentes
      casa= random.SystemRandom().choice([3,5,9])
      Pulo+=1
    elif casa==7:
      #Dado pela matriz de transição a probabilidade nas casas 3,7 tem probabilidade de 1/2 para as casa adjacentes
      casa=random.SystemRandom().choice([4,8])
      Pulo+=1
    elif casa==8:
      #Dado pela matriz de transição a probabilidade nas casas 2,4,6,8 tem probabilidade de 1/3 para as casa adjacentes
      casa= random.SystemRandom().choice([5,7,9])
      Pulo+=1
    elif casa==9:
      armadilha=True
      #Modificação para contagem de capturas pela armadilha A
      TrapB+=1

  return Pulo, TrapA, TrapB, Visita5

Pulos(5)

# Criando a função de media de capturas de cada armadilha, recebendo o parametro de interações desejadas 
def MediaArmadilhas(N):
  #Loop que avança a partir da casa 2 até a casa 9
  for i in range(2,9):
    TrpA=[]
    TrpB=[]
    #Loop que salva os valores das armadilhas
    for j in range(N):
      #Resgata uma tupla com os valores obtido nas simulações 
      Resultado = Pulos(i)
      TrpA.append(Resultado[1])
      TrpB.append(Resultado[2])
    #Calculando a porcentagem de cada armadilha ativada no espaço N
    MediaA=(sum(TrpA) / N)*100
    MediaB=(sum(TrpB) / N)*100
    #Formatando as variaveis para duas casas decimais no print
    FMediaA = "{:.2f}".format(MediaA)
    FMediaB = "{:.2f}".format(MediaB)
    print("Partindo da casa",i,"Com",N,"Interações")
    print("Captura pela Armadilha A =",FMediaA,"% - Captura pela Armadilha B =",FMediaB,"%")

MediaArmadilhas(5000)

# Criando a função de media de saltos, recebendo o parametro de interações necessarias
def MediaSaltos(N): 
  #Loop que avança a partir da casa 2 até a casa 9
  for i in range(2,9):
    Saltos=[]
    #Loop que faz a media de saltos na casa atual
    for j in range(N+1):
      #Resgata uma tupla com os valores obtido nas simulações
      Resultado = Pulos(i)
      #Salva a quantidade de saltos de cada interação 
      Saltos.append(Resultado[0])
    #Media salva somente o valor inteiro da media, pois nao é possivel dar 4,35 saltos
    Media=int(sum(Saltos) / N)
    print("A media de saltos dados a partir da casa",i,"é de",Media,"Com ",N,"Interações")

MediaSaltos(5000)

def MediaVisitas(N):
  #Loop que avança a partir da casa 2 até a casa 9
  for i in range(2,9):
    V5=[]
  #Loop que faz a media de saltos na casa 5
    for j in range(N+1):
      #Resgata uma tupla com os valores obtido nas simulações
      Resultado = Pulos(i)
      #Salva a quantidade de saltos de cada interação 
      V5.append(Resultado[3])
    #Media salva somente o valor inteiro da media, pois nao é possivel dar 4,35 saltos
    Media=int(sum(V5) / N)
    print("O numero de visitas a casa 5 partindo da casa",i,"é de em media",Media,"visitas Com ",N,"Interações")

MediaVisitas(10000)

def MediaVisita7(N):
  V7=[]
  for i in range(N+1): 
      #Resgata uma tupla com os valores obtido nas simulações
      Resultado = Pulos(7)
      #Salva a quantidade de saltos de cada interação 
      V7.append(Resultado[3])
  Media=(sum(V7) / N)
  print("O numero de visitas a casa 5 partindo da casa 7 é de em media",Media,"visitas Com ",N,"Interações")

MediaVisita7(10000)